sudo: required
services:
  - docker

before_install:
  - docker build -t suleman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suleman/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-eu-north-1-507196229912"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  

  

